[package]
name = "mechatron-screen-x11"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"

[target.'cfg(target_os = "linux")'.dependencies]
mechatron-shared = { path = "../shared" }
libc = "0.2"

[build-dependencies]
napi-build = "2"
